name: CI Pipeline

on:
  push:
    branches:
      - Develop
  pull_request:
    branches:
      - Develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Set environment variables
        run: |
          echo "JWT_SECRET_KEY=your-secret-key" >> $GITHUB_ENV
          echo "DB_USER=postgres" >> $GITHUB_ENV
          echo "DB_HOST=lazily-forgiving-hairtail.data-1.use1.tembo.io" >> $GITHUB_ENV
          echo "DB_DATABASE=postgres" >> $GITHUB_ENV
          echo "DB_PASSWORD=d1QVQlVnkfeULGNe" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV
          echo "PORT=5000" >> $GITHUB_ENV
      - name: Run tests
        run: |
          cd unittest
          python -m pytest
