name: CI Pipeline

on:
  push:
    branches:
      - Develop
  pull_request:
    branches:
      - Develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Set environment variables
        run: |
          echo "JWT_SECRET_KEY=your-secret-key" >> $GITHUB_ENV
      
      - name: Run tests
        env:
          DB_USER=postgres
          DB_HOST=lazily-forgiving-hairtail.data-1.use1.tembo.io
          DB_DATABASE=postgres
          DB_PASSWORD=d1QVQlVnkfeULGNe
          DB_PORT=5432
          PORT=5000
        run: |
          cd unittest
          python -m pytest
